spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/products?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: admin
    initialization-mode: always
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    hibernate:
      ddl-auto: validate

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  file: storage.log
  level:
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core:
      JdbcTemplate: DEBUG
      StatementCreatorUtils: TRACE

rabbitmq:
  queue: products.queue

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: never
      cache:
        time-to-live: 20000ms
    info:
      enabled: true

server:
  port: 8091
  servlet:
    context-path: /storage

info:
  build:
    group: @project.groupId@
    artifact: @project.artifactId@
    version: @project.version@
    name: @project.name@
